name: arch_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ijashuzain/arch_generator

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  path: ^1.8.0
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
  args: ^2.4.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build: ^2.3.1
  build_runner: ^2.3.3
  build_test: ^2.1.7
  freezed: ^2.3.3
  source_gen: ^1.3.0
